import type { Metadata } from "next"; 
import { Nunito } from "next/font/google"; 
import "./globals.css"; 
 
import Navbar from "@/app/components/Navbar/navbar"; 
 
import ClientOnly from "./components/ClientOnly"; 
import ToasterProvider from "@/app/providers/ToasterProvider"; 
 
import getCurrentUser from "./actions/getCurrentUser"; 
import ModalsProvider from "@/app/providers/ModalsProvider"; 
 
export const metadata: Metadata = { 
  title: "Create Next App", 
  description: "Generated by create next app", 
}; 
 
const font = Nunito({ 
  subsets: ["latin"], 
}); 
 
export default async function RootLayout({ 
  children, 
}: Readonly<{ 
  children: React.ReactNode; 
}>) { 
  const currentUser = await getCurrentUser(); 
 
  return ( 
    <html lang="en"> 
      <body className={font.className} suppressHydrationWarning> 
        <ClientOnly> 
          <ToasterProvider /> 
          <ModalsProvider /> 
          <Navbar currentUser={currentUser} /> 
        </ClientOnly> 
        <div className="pb-20 pt-28">{children}</div> 
      </body> 
    </html> 
  );
}